[project]
name = "fusion-rag-chatbot"
version = "0.1.0"
description = "Fusion RAG Chatbot with advanced retrieval capabilities"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    # Web framework
    "fastapi>=0.115.12",
    "uvicorn>=0.34.0",
    "python-multipart>=0.0.20",
    
    # LangChain ecosystem
    "langchain>=0.3.25",
    "langchain-community>=0.3.20",
    "langchain-core>=0.3.49", 
    "langchain-text-splitters>=0.3.7",
    
    # ML and Transformers
    "transformers>=4.50.3",
    "torch>=2.6.0",
    "tokenizers>=0.21.1",
    "huggingface-hub>=0.29.3",
    "safetensors>=0.5.3",
    
    # Vector database
    "chromadb>=0.5.20",
    
    # Document processing
    "pymupdf>=1.26.0",
    "pypdf>=5.4.0",
    
    # HTTP and API
    "requests>=2.32.3",
    "httpx>=0.28.1",
    "aiohttp>=3.11.14",
    
    # Configuration and environment
    "python-dotenv>=1.1.0",
    "pydantic>=2.11.0",
    "pydantic-settings>=2.8.1",
    
    # Core utilities
    "numpy>=2.2.4",
    "typing-extensions>=4.13.0",
    "tenacity>=9.0.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=8.0.0",
    "pytest-asyncio>=0.24.0",
    "black>=24.0.0",
    "isort>=5.13.0", 
    "flake8>=7.0.0",
    "mypy>=1.8.0",
]

monitoring = [
    "structlog>=23.2.0",
    "python-json-logger>=2.0.7",
    "prometheus-client>=0.19.0",
]

security = [
    "cryptography>=42.0.0",
    "python-jose>=3.3.0",
]

performance = [
    "aiofiles>=23.2.1", 
    "cachetools>=5.3.2",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.black]
line-length = 88
target-version = ['py313']

[tool.isort]
profile = "black"
line_length = 88

[tool.mypy]
python_version = "3.13"
strict = true
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
